### ISSUE TITLE
how to handle missing measurements?

### ISSUE THREAD

**Issue by ilaripih** [konimarti/kalman#4]
I admit I'm somewhat of a noob when it comes to Kalman filters but thanks to the good examples I got it working nicely. My problem is that I'm missing the measurement for some timestamps; usually just a single missing measurement but sometimes a few in a row.

The `Filter` interface only provides the `Apply` function which does both update and prediction. But apparently I should only do prediction without update when the measurement is missing? Or should I call `Apply` with an empty `z` and `ctrl` or something else?

**Comment by konimarti** [comment]
hi @ilaripih, glad it works nicely for you.

So far, I've not come across the problem of missing measurement data, so I can't tell you how  robust the Kalman filter would perform with missing measurements mathematically. 

A practical solution, however, would be to use the measurements values from the previous filter step (the estimate) as a substitute for the missing values. This would set the Kalman gain to practically zero and just perform a prediction step. 

See also [this link](https://math.stackexchange.com/questions/982982/kalman-filter-with-missing-measurement-inputs) for more information on this topic. Hope this helps and in case you adjust the code, please feel free to submit a pull request. Thanks!

**Comment by ilaripih** [comment]
Thanks for the swift response. Using the estimate as the measurement gave almost exactly the same results as skipping the update step. I'm happy with the results so closing this issue.
