### ISSUE TITLE
Reference for ROSE?

### ISSUE THREAD

**Issue by roger-** [konimarti/kalman#7]
Curious about what ROSE is. Is there a good reference?

**Comment by konimarti** [comment]
A good reference is the following book (in german): https://link.springer.com/book/10.1007/978-3-658-16728-8

Same author also published a paper about ROSE vs conventional Kalman filters [here](https://arxiv.org/abs/2108.11321).

Hope this helps

**Comment by roger-** [comment]
Thanks!

I don't understand German but it seems like they are using an innovation based measurement covariance estimate from an EWMA filter and a steady state Kalman gain (with some dependency on the covariance). 

Still not clear where the name comes from but this helps!

**Comment by konimarti** [comment]
ROSE = Rapid Ongoing Stochastic covariance Estimation
